### ISSUE TITLE
Contenu de la page HTML

### ISSUE THREAD

**Issue by StephaneSALVADOR** [StephaneSALVADOR/ProjetTP#1]
Pourrais-tu rajouter un contenu à la section 3 : Services.
Un titre et une simple phrase d'accroche suffit.

**Comment by Santrajinder** [comment]
ok

**Comment by Santrajinder** [comment]
`<!DOCTYPE` html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
    <h1>mon  titre 2 </h1>
    <h1>mon  titre 3 </h1>
    <h1>mon  titre 4 </h1>
    <h1>mon  titre 5 </h1>
    <h1>mon  titre 6 </h1>
    <h1>mon  titre 7 </h1>
    <h1>mon  titre 8 </h1>
    <h1>mon  titre 9 </h1>
    <h2>Carglass repare, Carglass remplace</h2>
    <label>Contact 0874561516115</label>
</body>
</html>`

**Comment by Santrajinder** [comment]
c'est fait

**Comment by StephaneSALVADOR** [comment]
Super merci
